### ISSUE TITLE
possible inconsistency between bash and js implementations?

### ISSUE THREAD

**Issue by safareli** [juliangruber/brace-expansion#11]
If I type it in bash i gate this result
```sh
$ echo foo bar{fiz,baz}
> foo barfiz barbaz
```
but using this module gives different result:
```javascript
> import expand from 'brace-expansion';
> expand('foo bar{fiz,baz}')
[ 'foo barfiz', 'foo barbaz' ]
```

Of course as a user of this module I could split input on space and then map over it, but it might be better to work as it works in bash.
what you think on that?

**Comment by juliangruber** [comment]
Yeah, bash treats the space specially. This would work the way brace-expansion currently does:

```bash
$ echo foo\ bar{fiz,baz}
foo barfiz foo barbaz
$ echo 'foo bar'{fiz,baz}
foo barfiz foo barbaz
```

Apparently a space splits the argument into multiple lists. I agree that this is surprising since it's not how bash works. At the same time, the space is kind of like bash's way of saying "those are two separate lists", which doesn't exist in JavaScript this way, so there's a point for not adding this to this lib.

We _could_ add this as an option.

@isaacs what do you think?

**Comment by safareli** [comment]
I thought about that too, just wanted to make sure if that's right behavior or not. I think there is no need to  add this option as of it will make it a bit complex.

**Comment by isaacs** [comment]
Another way to say this is that this module works like bash, if the strings are quoted.

```
$ echo "foo bar"{"fiz","baz"}
foo barfiz foo barbaz
```

Since JS doesn't have space-separated lists, it seems fine to me.  Another option might be ok, but whatever.
